import Head from 'next/head'
import { useSelector, useDispatch } from 'react-redux';
import { setPeople, setValue } from '@/redux/Store';
import { useState } from 'react';
import { useRouter } from 'next/router';
import Form from 'react-bootstrap/Form';
import { Button } from 'react-bootstrap';

export default function Home() {
  const router = useRouter()
  const numberOfPeople = useSelector((state) => state.people);
  const dispatch = useDispatch();
  const [inputs, setInputs] = useState(['']);

  const handleNumberOfPeopleChange = (e) => {
    const number = parseInt(e.target.value, 10);
  
    if (!isNaN(number) && number >= 0) {
      dispatch(setPeople(number));
    } else {
      dispatch(setPeople(null));
    }
  };

  const handleChange = (index, value) => {
    const newInputs = [...inputs];
    newInputs[index] = value;
    setInputs(newInputs);
  };

  const handleClick = () => {
    if (inputs.length === numberOfPeople && inputs.every((value) => value.trim() !== '')) {
      router.push('/Slot');
      dispatch(setValue(inputs));
    } else {
      alert('유저정보가 비어있습니다');
      return;
    }
  };

  console.log('inputs : ', inputs)
  console.log('numberOfPeople : ',numberOfPeople)

  return (
    <>
      <Head>
        <title>Who Coffe?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='mainGrid'>
        <h2>인원수를 선택해주세요</h2>
        <Form.Control
          type="number"
          id="numberOfPeople"
          placeholder='인원수를 입력해주세요'
          value={numberOfPeople}
          onChange={handleNumberOfPeopleChange}
        />
        {Array.from({ length: numberOfPeople }, (_, index) => (
          <div key={index}>
            <Form.Control
              type="text"
              id={`input${index + 1}`}
              placeholder='유저를 입력해주세요'
              onChange={(e) => handleChange(index, e.target.value)} />
          </div>
        ))}
        <Button
          disabled = {numberOfPeople === null || numberOfPeople === 0}
          onClick={() => { handleClick() }}
        >
          게임시작
        </Button>
      </div>
    </>
  )
}
