import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useSelector, useDispatch } from 'react-redux';
import { setPeople,setValue } from '@/redux/Store';
import { useState } from 'react';
import { useRouter } from 'next/router';
import Form from 'react-bootstrap/Form';
import { Button } from 'react-bootstrap';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter()
  const numberOfPeople = useSelector((state) => state.people); 
  const dispatch = useDispatch();
  const [inputs, setInputs] = useState(['']);

  const handleNumberOfPeopleChange = (e) => {
    const number = parseInt(e.target.value, 10);
    dispatch(setPeople(number));
  };

  const handleChange = (index, value) => {
    const newInputs = [...inputs];
    newInputs[index] = value;
    setInputs(newInputs);
  };

  const handleClick = () => {
    if (inputs.some((value) => value.trim() === '')) {
      alert('유저를 입력해주세요');
      return;
    } else {
      router.push('/Slot');
      dispatch(setValue(inputs));
    }
  };

  console.log('inputs : ',inputs)

  return (
    <>
      <Head>
        <title>Who Coffe?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Form.Label htmlFor="numberOfPeople">인원 수 선택: </Form.Label>
        <Form.Control
          type="number"
          id="numberOfPeople"
          value={numberOfPeople}
          onChange={handleNumberOfPeopleChange}
        />
        {Array.from({ length: numberOfPeople }, (_, index) => (
          <div key={index}>
            <Form.Label htmlFor={`input${index + 1}`}>{`입력 ${index + 1}: `}</Form.Label>
            <Form.Control type="text" id={`input${index + 1}`} onChange={(e) => handleChange(index, e.target.value)}/>
          </div>
        ))}
        <Button onClick={()=>{handleClick()}}>게임시작</Button>
      </div>
    </>
  )
}
